using EpicJewels.GemEffects;
using Jewelcrafting;
using System;
using System.Text;
using UnityEngine;

namespace EpicJewels
{
    public static class CustomGems
    {
        public static void AddGems()
        {
            API.AddGems("Jade", "jade", new Color(0.031f, 0.69f, 0.043f, 1f));
            API.AddGems("Amber", "amber", new Color(1f, 0.776f, 0.071f, 1f));
            API.AddGems("Aquamarine", "aquamarine", new Color(0.259f, 0.663f, 0.71f, 1f));
            API.AddGems("Garnet", "garnet", new Color(1f, 0.141f, 0.039f));
            API.AddGems("Opal", "opel", new Color(0.945f, 0.988f, 0.988f, 1f));
            API.AddGems("Amethyst", "amethyst", new Color(0.784f, 0.302f, 0.98f, 1f));
            StringBuilder sb = new();
            sb.AppendLine("AddSlashDamage:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [3, 6, 9]");
            sb.AppendLine("AddChopDamage:");
            sb.AppendLine("  slot: tool");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [6, 9, 12]");
            sb.AppendLine("CoinHoarder:");
            sb.AppendLine("  slot: cloak");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [1, 2.5, 5]");
            sb.AppendLine("CoinGreed:");
            sb.AppendLine("  slot: utility");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [5, 10, 20]");
            sb.AppendLine("SlashResistance:");
            sb.AppendLine("  slot: chest");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("ExpertAcrobat:");
            sb.AppendLine("  slot: legs");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("ExpertDaggers:");
            sb.AppendLine("  slot: head");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("AddSlashDamage:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: jade");
            sb.AppendLine("  power: [3, 6, 9]");
            sb.AppendLine("BluntResistance:");
            sb.AppendLine("  slot: legs");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("ExpertSmasher:");
            sb.AppendLine("  slot: chest");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("AddBluntDamage:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [3, 6, 9]");
            sb.AppendLine("ExpertSpearmaiden:");
            sb.AppendLine("  slot: cloak");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("BlockReduceStamina:");
            sb.AppendLine("  slot: shield");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [10, 15, 20]");
            sb.AppendLine("WeaponReducedStamina:");
            sb.AppendLine("  slot: utility");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [5, 10, 15]");
            sb.AppendLine("IncreaseStaminaRegen:");
            sb.AppendLine("  slot: head");
            sb.AppendLine("  gem: amber");
            sb.AppendLine("  power: [9, 18, 27]");
            sb.AppendLine("PierceResistance:");
            sb.AppendLine("  slot: chest");
            sb.AppendLine("  gem: aquamarine");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("ExpertSprinter:");
            sb.AppendLine("  slot: head");
            sb.AppendLine("  gem: aquamarine");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("AddPierceDamage:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: aquamarine");
            sb.AppendLine("  power: [3, 6, 9]");
            sb.AppendLine("WaterSwiftness:");
            sb.AppendLine("  slot: legs");
            sb.AppendLine("  gem: aquamarine");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("WaterFrenzy:");
            sb.AppendLine("  slot: utility");
            sb.AppendLine("  gem: aquamarine");
            sb.AppendLine("  power: [6, 9, 18]");
            sb.AppendLine("WaterResistant:");
            sb.AppendLine("  slot: cloak");
            sb.AppendLine("  gem: aquamarine");
            sb.AppendLine("  power: [15, 30, 60]");
            sb.AppendLine("FireResistance:");
            sb.AppendLine("  slot: legs");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("ExpertAxemaster:");
            sb.AppendLine("  slot: chest");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("ExpertMage:");
            sb.AppendLine("  slot: head");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("Inferno:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [20, 40, 60]");
            sb.AppendLine("AddPickaxeDamage:");
            sb.AppendLine("  slot: tool");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [6, 9, 12]");
            sb.AppendLine("BurningFrenzy:");
            sb.AppendLine("  slot: utility");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [6, 9, 18]");
            sb.AppendLine("BurningViking:");
            sb.AppendLine("  slot: cloak");
            sb.AppendLine("  gem: garnet");
            sb.AppendLine("  power: [5, 15, 30]");
            sb.AppendLine("AddLightningDamage:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [6, 9, 12]");
            sb.AppendLine("ExpertFisher:");
            sb.AppendLine("  slot: head");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("ExpertHarvester:");
            sb.AppendLine("  slot: tool");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("ExpertPolearms:");
            sb.AppendLine("  slot: chest");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("ReduceWeight:");
            sb.AppendLine("  slot: utility");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [2, 4, 6]");
            sb.AppendLine("LightningResistance:");
            sb.AppendLine("  slot: legs");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("CoverOfDarkness:");
            sb.AppendLine("  slot: cloak");
            sb.AppendLine("  gem: opel");
            sb.AppendLine("  power: [10, 15, 30]");
            sb.AppendLine("AddSpiritDamage:");
            sb.AppendLine("  slot: ['weapon', 'elementalmagic', 'bow', 'crossbow']");
            sb.AppendLine("  gem: amethyst");
            sb.AppendLine("  power: [9, 12, 18]");
            sb.AppendLine("ExpertSwordsman:");
            sb.AppendLine("  slot: chest");
            sb.AppendLine("  gem: amethyst");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("IncreaseStamina:");
            sb.AppendLine("  slot: utility");
            sb.AppendLine("  gem: amethyst");
            sb.AppendLine("  power: [6, 9, 15]");
            sb.AppendLine("IncreaseEitr:");
            sb.AppendLine("  slot: head");
            sb.AppendLine("  gem: amethyst");
            sb.AppendLine("  power: [6, 9, 15]");
            sb.AppendLine("ExpertBrawler:");
            sb.AppendLine("  slot: legs");
            sb.AppendLine("  gem: amethyst");
            sb.AppendLine("  power: [5, 7, 12]");
            sb.AppendLine("PoisonResistance:");
            sb.AppendLine("  slot: cloak");
            sb.AppendLine("  gem: amethyst");
            sb.AppendLine("  power: [1, 3, 5]");
            sb.AppendLine("gems:");
            sb.AppendLine("  meadows:");
            sb.AppendLine("    aquamarine: 0.1");
            sb.AppendLine("    amber: 0.1");
            sb.AppendLine("    jade: 0.3");
            sb.AppendLine("  black forest:");
            sb.AppendLine("    jade: 0.1");
            sb.AppendLine("    garnet: 0.1");
            sb.AppendLine("    opel: 0.1");
            sb.AppendLine("  swamp:");
            sb.AppendLine("    amber: 0.2");
            sb.AppendLine("    garnet: 0.2");
            sb.AppendLine("    opel: 0.1");
            sb.AppendLine("  mountain:");
            sb.AppendLine("    aquamarine: 0.4");
            sb.AppendLine("    jade: 0.2");
            sb.AppendLine("    amethyst: 0.1");
            sb.AppendLine("  plains:");
            sb.AppendLine("    amber: 0.4");
            sb.AppendLine("    garnet: 0.4");
            sb.AppendLine("    opel: 0.1");
            sb.AppendLine("  mistlands:");
            sb.AppendLine("    aquamarine: 0.2");
            sb.AppendLine("    amethyst: 0.4");
            sb.AppendLine("    opel: 0.1");
            sb.AppendLine("  ash lands:");
            sb.AppendLine("    amethyst: 0.2");
            sb.AppendLine("    garnet: 0.4");
            sb.AppendLine("    opel: 0.1");
            API.AddGemConfig(sb.ToString());
        }
    }
}
